#!/usr/bin/env python3

import argparse, subprocess

parser = argparse.ArgumentParser(
                    prog='stopCDN',
                    description='Shut down the CDN system',
                    epilog='./stopCDN [-p port] [-o origin] [-n name] [-u username] [-i keyfile]')
parser.add_argument('-p', '--port')
parser.add_argument('-o', '--origin')
parser.add_argument('-n', '--name')
parser.add_argument('-u', '--username')
parser.add_argument('-i', '--keyfile')

args = parser.parse_args()

with open('httpservers.txt', 'r') as r_file:
    for line in r_file:
        domain = line.split()[0]
        process = subprocess.Popen(['ssh', '-i', args.keyfile, f'{args.username}@{domain}'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
        process.communicate('screen -ls | grep \'(Detached)\' | awk \'{print $1}\' | xargs -I % -t screen -X -S % quit')